nerf:
  epochs: 10
  device: 'cpu'
  model_name: 'nerf'
  model_args:
    input_dim_position: 3
    input_dim_view: 3
    hidden_dim: 256
    output_dim: 3
    embedding_size_position: 10
    embedding_size_view: 4
  optimizer: 'SGD'
  optimizer_args:
    lr: 0.0005
  scheduler: 'ExponentialLR'
  scheduler_args:
    gamma: 0.99997
  loss_function: 'MSELoss'
  dropout: None
  data_set_name: 'SyntheticDataset'
  data_set_args:
    root_folder: './preprocessed_data'
    rays_per_image: 128
  data_loader_args:
    batch_size: 1
    shuffle: True




